volumes:
    postgres:
    prometheus:
    grafana:

networks:
    default:
        name: unleash-demo
        driver: bridge

services:
    app:
        hostname: app
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - .:/app:rw
        ports:
            - "8080:8080"
        depends_on:
            - unleash
            - redis

    unleash:
        hostname: unleash
        image: unleashorg/unleash-server:6
        environment:
            DATABASE_URL: postgres://unleash:unleash@postgres/unleash
            DATABASE_SSL: 'false'
            DATABASE_SCHEMA: public
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_NAME: unleash
            DATABASE_USERNAME: unleash
            DATABASE_PASSWORD: unleash
        ports:
            - "4242:4242"
        depends_on:
            - postgres

    postgres:
        hostname: postgres
        image: postgres:16.3
        environment:
            POSTGRES_DB: unleash
            POSTGRES_USER: unleash
            POSTGRES_PASSWORD: unleash
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        hostname: redis
        image: redis:7.4
        ports:
            - "6379:6379"

    prometheus:
        hostname: prometheus
        image: prom/prometheus:v3.0.0
        ports:
            -   "9090:9090"
        volumes:
            -   ./docker/prometheus/config.yaml:/etc/prometheus/prometheus.yml:ro
            -   prometheus:/prometheus
        depends_on:
            -   app

    grafana:
        hostname: grafana
        image: grafana/grafana:11.3.1
        ports:
            -   "3000:3000"
        volumes:
            -   grafana:/var/lib/grafana
        depends_on:
            -   prometheus

    k6:
        hostname: k6
        image: grafana/k6:0.55.0
        environment:
            - K6_PROMETHEUS_RW_SERVER_URL=http://localhost:9090/api/v1/write
        volumes:
            -   ./benchmarks/k6:/app
        command: run example.js
        depends_on:
            -   app
